USER_ID = 'q93w4q3zxj1v'
# Your PAT (Personal Access Token) can be found in the portal under Authentification
PAT = 'e0e78f3f6a9f4a64a434c5fae6d6b332'
APP_ID = 'e497f7b005b1473589909eed35827f0b'
WORKFLOW_ID = 'Clarifai_WORKFLOW_ID'
WORKFLOW_ID_TEXT = 'Clarifai_WORKFLOW_ID'
WORKFLOW_ID_IMAGE = '0b59b93d35864b9b88699a557629babf'
WORKFLOW_ID_STORY_GPT3 = 'Clarifai_WORKFLOW_ID'
